---
spec:
  scope: Namespaced
  group: drowzee.challengr.io
  names:
    kind: SleepSchedule
    plural: sleepschedules
    singular: sleepschedule
    shortNames:
      - ss
  versions:
    - name: v1beta1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                        enum:
                          - 'True'
                          - 'False'
                      type:
                        type: string
                      lastHeartbeatTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                observedGeneration:
                  type: integer
            spec:
              type: object
              required:
                - sleepTime
                - timezone
                - wakeTime
                - deployments
              properties:
                deployments:
                  type: array
                  description: The deployments that will be slept/woken.
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                sleepTime:
                  type: string
                  description: 'The time that the deployment will start sleeping(format: HH:MMam/pm)'
                wakeTime:
                  type: string
                  description: 'The time that the deployment will wake up (format: HH:MMam/pm)'
                timezone:
                  type: string
                  description: The timezone that the input times are based in
                ingressName:
                  type: string
                  description: The ingress that will be slept/woken.
      additionalPrinterColumns:
        - name: sleepTime
          type: string
          description: Starts Sleeping
          jsonPath: .spec.sleepTime
        - name: wakeTime
          type: string
          description: Wakes Up
          jsonPath: .spec.wakeTime
        - name: timezone
          type: string
          description: Timezone
          jsonPath: .spec.timezone
        - name: deployments
          type: string
          description: Deployments
          jsonPath: .spec.deployments[*].name
        - name: naptime?
          type: string
          description: Time for a nap?
          jsonPath: .status.conditions[?(@.type == "naptime")].status
        - name: ingressBackup?
          type: string
          description: Ingress Backup
          jsonPath: .status.conditions[?(@.type == "ingressBackup")].status
      subresources:
        status: {}
      served: true
      storage: true
      deprecationWarning:
metadata:
  name: sleepschedules.drowzee.challengr.io
  labels:
    k8s-app: drowzee
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
metadata:
  name: drowzee
  labels:
    k8s-app: drowzee
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
rules:
  - resources:
      - customresourcedefinitions
    apiGroups:
      - apiextensions.k8s.io
    verbs:
      - '*'
  - resources:
      - leases
    apiGroups:
      - coordination.k8s.io
    verbs:
      - '*'
  - resources:
      - sleepschedules
    apiGroups:
      - drowzee.challengr.io
    verbs:
      - '*'
  - resources:
      - sleepschedules/status
    apiGroups:
      - drowzee.challengr.io
    verbs:
      - '*'
  - resources:
      - events
    apiGroups:
      - events.k8s.io
    verbs:
      - '*'
  - resources:
      - deployments
    apiGroups:
      - "apps"
    verbs:
      - '*'
  - resources:
      - ingresses
    apiGroups:
      - networking.k8s.io
    verbs:
      - '*'
  - resources:
      - services
      - configmaps      
    apiGroups:
      - ""
    verbs:
      - '*'

---
metadata:
  name: drowzee
  labels:
    k8s-app: drowzee
  namespace: default
kind: ServiceAccount
apiVersion: v1

---
metadata:
  name: drowzee
  labels:
    k8s-app: drowzee
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
roleRef:
  name: drowzee
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: drowzee
    kind: ServiceAccount
    namespace: default
