apiVersion: drowzee.challengr.io/v1beta1
kind: SleepSchedule
metadata:
  name: testing
spec:
  sleepTime: "10:00pm"
  wakeTime: "09:00am"
  timezone: "Australia/Sydney"
  deployments:
    - name: dummy-service
  ingressName: dummy-service
---
apiVersion: drowzee.challengr.io/v1beta1
kind: SleepSchedule
metadata:
  name: service1
  namespace: services
spec:
  sleepTime: "10:00pm"
  wakeTime: "09:00am"
  timezone: "Australia/Sydney"
  deployments:
    - name: service1
    - name: service1-worker
  ingressName: service1
---
apiVersion: drowzee.challengr.io/v1beta1
kind: SleepSchedule
metadata:
  name: service2
  namespace: services
spec:
  sleepTime: "10:00pm"
  wakeTime: "09:00am"
  timezone: "Australia/Sydney"
  deployments:
    - name: service2
    - name: service2-worker
  ingressName: service2
---
apiVersion: drowzee.challengr.io/v1beta1
kind: SleepSchedule
metadata:
  name: permanent-down
  namespace: services
spec:
  sleepTime: "08:00pm"
  # No wakeTime defined - resources will remain scaled down indefinitely
  timezone: "Australia/Sydney"
  deployments:
    - name: non-prod-service
  statefulsets:
    - name: non-prod-database
  cronjobs:
    - name: non-prod-backup
  ingressName: non-prod-service
