{{- if eq .Values.mode "single_namespace" -}}
metadata:
  name: drowzee
  labels:
    k8s-app: drowzee
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
rules:
  - resources:
      - customresourcedefinitions
    apiGroups:
      - apiextensions.k8s.io
    verbs:
      - '*'
  - resources:
      - leases
    apiGroups:
      - coordination.k8s.io
    verbs:
      - '*'
  - resources:
      - sleepschedules
    apiGroups:
      - drowzee.challengr.io
    verbs:
      - '*'
  - resources:
      - sleepschedules/status
    apiGroups:
      - drowzee.challengr.io
    verbs:
      - '*'
  - resources:
      - events
    apiGroups:
      - events.k8s.io
    verbs:
      - '*'
  - resources:
      - deployments
      - statefulsets
      - cronjobs
    apiGroups:
      - "apps"
      - "batch"
    verbs:
      - '*'
  - resources:
      - ingresses
    apiGroups:
      - networking.k8s.io
    verbs:
      - '*'
  - resources:
      - services
      - configmaps      
    apiGroups:
      - ""
    verbs:
      - '*'
{{- end }}